name: Jakob Anderson
description: Fighting for Performance and Craft at the Front-lines
meta_description: "Fighting for Performance and Craft at the Front-lines"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 13
baseurl: /
domain_name: 'https://jakobanderson.com'
google_analytics: 'UA-11240242-6'
gems: [jekyll-paginate]
permalink: /:title/

include: /.well-known/

# Details for the RSS feed generator
url:            'https://jakobanderson.com'
author:         'Jakob Anderson'
author_description: 'Full-Stack JavaScript Developer, Web Performance Champion'
# author_thumb:   true

permalink: /:title/

defaults:
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      author: "Jakob Anderson"
