name: Jakob Anderson
description: Fighting for Performance and Craft at the Front-lines
meta_description: "Fighting for Performance and Craft at the Front-lines"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 13
baseurl: /
domain_name: 'https://blog.jakobanderson.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://blog.jakobanderson.com'
author:         'Jakob Anderson'

permalink: /:title/

defaults:
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      author: "Jakob Anderson"